# Generated by Django 3.2.3 on 2021-07-15 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitante',
            old_name='registrador_por',
            new_name='registrado_por',
        ),
    ]
